---
sidebar: sidebar 
permalink: access-control.html 
keywords: role-based access control, rbac, user permissions, app admin, project admin 
summary: NetApp Data Migratorは、ロールベースアクセス制御（RBAC）を使用してユーザー権限を管理し、App Adminユーザーが他のユーザーにロールを割り当てることができます。 
---
= NetApp Data Migrator のアクセス制御を管理する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Data Migratorは、ロールベースアクセス制御（RBAC）を使用してユーザー権限を管理します。RBACを使用すると、App Adminユーザー（管理者）は、他のユーザーに以下の3つのロールのいずれかを割り当てることができ、安全なアクセス制御と効率的な運用が保証されます。App Adminユーザーは、それぞれの責任とアクセス要件に基づいて、他のユーザーに権限を付与します。

* *App Admin*：このアクセス レベルでは、ユーザーがシステム全体の設定、ユーザーのロール、およびアクセス権限を管理できます。
* *Project Admin*: このアクセス レベルでは、ユーザーはジョブの設定や実行を含む、特定の移行プロジェクトを管理できます。
* *Project Viewer*：このアクセス レベルでは、ユーザーに移行の進捗状況、ログ、レポートを監視するための読み取り専用アクセス権限が提供されます。このロールは、データ移行プロジェクトの進捗状況を監視・観察する必要があるものの、プロジェクトを変更したり妨害したりする可能性のある操作を実行する必要のないユーザーを対象としています。


次の表に、アクションとユーザ ロール権限の概要を示します。

[cols="1,2,1,1,1a"]
|===
| アクション | 概要 | アプリ管理者 | プロジェクト管理者 | プロジェクト ビューアー 


| エージェントの導入 | ユーザーは*ワーカー設定手順の表示*にアクセスできます。 | はい | はい  a| 
いいえ



| ユーザを作成 | ユーザーは新しいユーザーアカウントを作成できます | はい | いいえ  a| 
いいえ



| ユーザーのリスト | ユーザーはユーザー一覧を表示できます | はい | はい  a| 
はい



| 設定の管理 | ユーザーは構成設定を管理できます | はい | はい  a| 
いいえ



| ジョブを管理する | ユーザーは移行ジョブを管理できます | はい | はい  a| 
いいえ



| レポート | ユーザーはレポートをダウンロードするためのオプションにアクセスできます | はい | はい  a| 
はい



| プロジェクトの更新 | ユーザーはプロジェクトを編集できます | はい | はい  a| 
いいえ



| プロジェクトを表示 | ユーザーはプロジェクト一覧ページにアクセスできます | はい | はい  a| 
はい



| プロジェクトを作成する | ユーザーはプロジェクトを作成できます | はい | いいえ  a| 
いいえ



| SMTPを保存 | ユーザは SMTP の詳細を追加または編集できます | はい | いいえ  a| 
いいえ

|===