---
sidebar: sidebar 
permalink: configure-bulk-cutover.html 
keywords: bulk cutover, final sync, cutover job, chain of custody, migration approval 
summary: NetApp Data Migratorで一括カットオーバーを使用して、ソースシステムと宛先システム間の最終的なデータ同期を実行します。 
---
= NetApp Data Migrator での一括カットオーバーの設定
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Data Migratorで一括カットオーバーを使用して、ソースシステムと宛先システム間の最終同期を実行します。ベースライン移行が完了し、増分同期が実行されている場合は、複数のパスを1つのカットオーバージョブに統合できます。



== カットオーバー ジョブを開始する

切り替え作業を開始するには、以下の手順に従ってください。

.手順
. NetApp Data Migratorにログインします。
. *Storage Servers* > *File Servers* を選択します。
. カットオーバージョブを作成するファイルサーバーの名前を選択してください。
. *一括切り替え*を選択します。
. *Select Path* ページで、 *Source Path* の横にあるチェックボックスを選択します。
. ソースパスの横にあるチェックボックスを選択します（カットオーバージョブを確定します）。
. *続行*を選択します。
. ジョブ名の横にあるチェックボックスを選択して、*一括切り替え*ジョブを開始することを確認してください。
+

NOTE: バルク移行ジョブが並行して実行されている場合、ジョブを選択できます。

. 一括切り替え作業を開始するには、*Submit*を選択してください。
+
*カットオーバージョブが作成されました*という確認メッセージが表示されます。

. このメッセージの横にある*ジョブリストの表示*リンクを選択すると、新しいジョブが表示されているジョブ設定リストページが開きます。




== 一括切り替えジョブを承認する

切り替え作業を承認するには、以下の手順に従ってください。

.手順
. *Jobs*ページで、*Job Run List*タブを選択します。
. カットオーバージョブの横にあるアクションメニューを選択します。
. *Review* を選択します。
+
*Cutover Confirmation* ポップアップボックスが表示されます。

. *Download CoC Report* リンクを選択します。
+
レポートを確認し、切り替えが成功したかどうか、またすべてのデータがソースから宛先へ正常に移行されたかどうかを確認してください。

. *I have reviewed and verified the COC document and all other essential information* の横にあるチェックボックスを選択します。
. COCレポートの情報に問題がなければ、*確認*を選択して*一括切り替え*を承認してください。
+
ステータスが*完了*に変更されます。


