---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: known, limitations, nfs limits, smb limits, worker sizing, migration restrictions 
summary: NetApp Data Migratorの既知の制限事項を理解することで、移行作業をより効率的に行うことができます。 
---
= NetApp Data Migratorの既知の制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NFSおよびSMBの移行に関する制限事項、およびこのバージョンでは動作しない、または正常に動作しない機能については、ここに記載されています。これらの制限事項をよくお読みください。



== NFSおよびSMBの検出と移行に関する制限

[cols="1,2,2a"]
|===
| 概要 | NFS | SMB 


| 同時に実行できるエクスポート パスの数 | 4  a| 
2



| ディレクトリ内のファイルの最大数 | 1 million  a| 
1 million



| ワーカーのサイジング | 4コアCPU、16GBメモリ  a| 
16コアCPU、64GBメモリ



| コントロールプレーンのサイジング | 8コアCPU、64GBメモリ  a| 
8コアCPU、64GBメモリ



| エクスポートパス内のファイルの最大数 | 20 million  a| 
20 million

|===


== 機能の制限

[cols="1,2a"]
|===
| 概要 | 制限 


| アクティブな宛先のサポート  a| 
NetApp Data Migrator は、アクティブな宛先（カットオーバー前にターゲットストレージがアクティブに使用または書き込みされている場合）をサポートしていません。



| 大文字と小文字を区別するファイル  a| 
SMBの場合、NetApp Data Migratorは、フォルダ内でNFSを使用して作成された大文字小文字が異なるファイルのうち、1つだけを移行し、もう1つのファイルについてはエラーを発生させます。これは、SMBが両方のファイルを受け入れることができないために発生します。NFSを使用して検出を実行すると、これらの大文字小文字を区別するファイルを識別できます。



| ネットワークアクセシビリティ  a| 
NetAppでは、プライベート ネットワークでNetApp Data Migratorを使用することを推奨します。



| NFSv4 ACL  a| 
NetApp Data MigratorはNFSv4でアクセス制御リスト（ACL）をスタンプするのではなく、宛先に基本的なアクセス許可のみを適用します。この動作はNFSv3と同様です。



| プロトコル移行 - タイプ  a| 
プロトコル間の移行はサポートされていません。たとえば、NFSからSMBへの移行などです。



| プロトコル移行 - Version  a| 
同一プロトコル内でのバージョン間の移行はサポートされていません。たとえば、NFSv3からNFSv4への移行などです。



| SMB 権限  a| 
NetApp Data Migratorは、SMBシステムアクセス制御リスト（SACL）（監査権限）の移行をサポートしていません。



| 末尾にスペースを含む SMB ファイル  a| 
SMB経由で移行する場合、NetApp Data Migratorは、ファイル名の末尾にスペースが含まれているファイルに対してエラーを発生させます。これは、SMBがそのようなファイル名を許可していないためです。



| SMB 特殊ファイル  a| 
NetApp Data Migratorはリダイレクト（シンボリックリンク、ハードリンク、ジャンクションポイント、代替データストリーム（ADS）、ボリュームマウントポイント）を検出し、検出後にそれらを報告します。ADS、スパースファイル、およびSMBリダイレクトの移行はサポートされていません。



| セキュリティ  a| 
NetApp Data Migratorは、自己署名証明書を使用してWebトラフィックをSSL/TLSで暗号化します。



| スパース ファイル  a| 
スパースファイルは移行時にフルサイズファイルになります。NetApp Data Migratorはスパース性を保持しません。これらのファイルには追加のストレージが必要です。



| システムファイル  a| 
NetApp Data Migratorは、ソースが所有するシステム生成ファイルを移行することはできません。



| ユーザーインターフェース  a| 
NetApp Data Migratorは、1920 x 1080の画面解像度を使用するGoogle ChromeおよびFirefoxブラウザ向けに最適化されています。モバイルディスプレイはサポートされていません。



| Windowsワーカーの導入  a| 
Windowsワーカーは、宛先と同じルートドメインに属している必要があります。

|===