---
sidebar: sidebar 
permalink: learn-about-install.html 
keywords: aws installation, prerequisites, control plane, worker vm, ec2 
summary: NetApp Data MigratorのコントロールプレーンとワーカーVMのインストールについて説明します。 
---
= NetApp Data Migrator のインストールについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Data Migratorは、制御プレーンと1つ以上のワーカーで構成され、これらが連携してNFSおよびSMBトランスポートプロトコルを使用してデータ移行ジョブを実行します。

* *コントロール プレーン*：コントロール プレーンは、中央管理および制御レイヤとして機能します。まず、Linux仮想マシン（VM）上にコントロール プレーンをデプロイし、次にワーカーをデプロイします。
* *ワーカー*：ワーカーとは、実際のデータ移行を実行する仮想マシンです。規模や要件に応じて、複数のワーカーをデプロイできます。ワーカーの種類はプロトコルによって異なります：
+
** LinuxワーカーはNFS移行をサポートします。
** Windows ワーカーは SMB 移行をサポートします。




まず、AWS、Azure、またはGoogle Cloudサービスを使用するか、Open Virtual Appliance（OVA）テンプレートを使用して、コントロールプレーン仮想マシン（VM）とLinuxワーカーVMをデプロイします。NetApp Support Siteから、導入に必要なNetApp Data Migratorイメージをダウンロードします。

導入後、コントロールプレーンVMとワーカーVMを作成して、NetApp Data Migratorにアクセスします。導入されたイメージを使用して、コントロールプレーンVMとLinuxワーカーVMを作成します。NetApp Support SiteからダウンロードしたWindows Worker Installerを使用して、WindowsワーカーVMを作成します。その後、オプションでコントロールプレーンVMを検証するか、NetApp Data Migrator UIにアクセスしてコントロールプレーンとワーカーに接続することができます。

.次の手順
NetApp Data Migratorのインストールについて学習した後は、新規のお客様の場合はNetApp Support Siteでlink:register-for-account.html["アカウントを登録"]するか、すでにアカウントをお持ちの場合はlink:deploy-control-plane-and-linux-workers.html["コントロールプレーンとLinuxワーカーVMを導入する"]に進むことができます。
