---
sidebar: sidebar 
permalink: manage-file-servers.html 
keywords: file servers, nfs, smb, worker association, export paths 
summary: NetApp Data Migratorを使用して、NFSまたはSMBプロトコルを使用するファイルサーバーを追加、設定、編集します。 
---
= ファイル サーバの追加と管理
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Data Migratorを使用して、NFSまたはSMBプロトコルを使用するファイルサーバーを追加、設定、編集できます。



== 新しいファイルサーバーを追加する

新しいNFSまたはSMBファイルサーバーを追加し、ワーカー仮想マシンを設定します。

システム構成に応じて、「その他の NAS」または「Dell Isilon」のワークフロー オプションを使用してください。

[role="tabbed-block"]
====
.NAS：その他
--
.手順
. 左側のナビゲーションパネルで、* Storage Servers * を選択します。
. *ファイルサーバー* > *+追加* を選択します。
+
*ファイル サーバー*ページが開き、続いて*サーバーの種類*ページが表示されます。

. サーバー名を入力し、*サーバータイプ*で*その他のNAS*を選択します。
+
* Credentials * ページが開きます。

. NFSまたはSMBサーバーの*ホスト名*（またはIPアドレス）を入力します。
. *NFS*ファイルサーバーを使用している場合：
+
** NFSファイル共有にアクセスするための*ユーザー名*を入力してください。
** 必要に応じて、*パスワード*を入力してください。
** NFS の *プロトコル バージョン* を選択します。
** *Export Paths Retrieval Mechanism* パネルで、*Auto Discover* または *Manual Upload* を選択します：
+
*Auto Discover*はエクスポートパスを自動的に検出します。

+
*手動アップロード*は、エクスポートパスを手動でアップロード、またはGoogle Cloud NetApp Volumes（GCNV）Flexサービスなど*自動検出*がサポートされていない環境でアップロードします。ファイルサーバーを追加した後、<<manually-upload-export-paths,エクスポートパスを手動でアップロードする必要があります>>。



. *SMB* ファイル サーバを使用している場合：
+
** SMB ファイル共有にアクセスするための *ユーザー名* を入力します。
** *パスワード* を入力します。
** SMB の*プロトコル バージョン*を選択します。


. *Workers* タブを選択します。
+
.. *関連付け済み*列で、サーバーに関連付けたい1つ以上のワーカーの横にあるトグルボタンを選択します。
.. *続行*を選択すると、選択した 1 つ以上のワーカーがNetApp Data Migratorへの接続性を持っているかどうかをテストする事前チェック操作が開始されます。


. 事前チェックが完了したら、検出されたエラーをすべて解決してください。（エラーの解決方法の詳細については、ファイルサーバーのよくある質問（FAQ）を参照してください。）
+
事前チェックがエラーなく完了したら、*Job Config* タブを選択し、*Finish* を選択します。File Server の名前が *File Servers* のリストに表示されます。

+
ファイル サーバのステータスは、*ファイル サーバ*テーブルの*ステータス*列に表示されます。ステータスのタイプには次のものがあります：

+
** *アクティブ*：エラーはなく、すべての詳細が検証済みです。
** *処理中：* サーバーの検証が進行中です。
** *Draft*: ファイルサーバーに関連付けられたワーカーはいません。
** *エラーが発生しました*：権限に問題があるか、利用可能なパスがないか、エクスポートパスとして / しか利用できません。ファイルサーバー作成時にエクスポートパスとして *Auto Discovery* を選択した場合、これらの問題が発生する可能性があります。




--
.Dell Isilon
--
.手順
. 左側のナビゲーションパネルで、* Storage Servers * を選択します。
. *ファイルサーバー* > *+追加* を選択します。
+
*ファイル サーバー*ページが開き、続いて*サーバーの種類*ページが表示されます。

. Isilon ファイル サーバの*構成名*を入力します。
. * Server Type *ドロップダウンから* Dell Isilon *を選択します。
+
*Management Console* セクションが開きます：

. *管理ホスト*（Isilon管理コンソールのホスト名またはIPアドレス）を入力します。
. Isilon管理APIにアクセスするための*ユーザー名*を入力してください。
. *パスワード* を入力します。
. *続行*を選択して、IsilonクラスタからTLS証明書を取得します。
. モーダルに表示されている*TLS証明書*の詳細を確認してください：
+
.. 証明書の発行者、有効期限、およびフィンガープリントを確認してください。
.. 証明書を信頼して続行するには、* Accept * を選択します。
.. 証明書を信頼できない場合は、* Reject * を選択してキャンセルしてください。


. *Zone Credentials* ページが開きます：
+
.. 検出された利用可能なゾーンの中から、1つ以上の*アクセスゾーン*を選択してください。
.. 選択したゾーンごとに、プロトコルクレデンシャルを設定します。
.. ドロップダウンから* NFS IP アドレス*を選択します。
.. NFSエクスポートパスにアクセスするための*Username*を入力します。
.. *SMB IP Address* を入力します。
.. SMB ファイル共有にアクセスするための *ユーザー名* を入力します。
.. *パスワード* を入力します。


+

NOTE: IsilonクラスタでSmartConnectサービスIP（SSIP）が設定されている場合、IPアドレスのドロップダウンリストからSmartConnectゾーンドメイン名を選択できます。SSIP対応ドメイン名を使用する場合、Isilon SmartConnectインフラストラクチャが接続のロード バランシングを管理し、ストレージ レイヤで解決します。NetApp Data Migratorは、この構成では追加のロード バランシングを実行しません。

. *Workers* タブが開きます：
+
.. 各ゾーンとプロトコルの組み合わせごとに、ワーカーを割り当てます：
+
*関連付け済み*列で、関連付けたい1人以上の作業者の横にあるトグルボタンを選択します。

.. * Proceed * を選択すると、選択した 1 つ以上のワーカーが NetApp Data Migrator および Isilon ファイル サーバへの接続性を持っているかどうかをテストする事前チェック処理が開始されます。


. 事前チェックが完了したら、フラグが付けられたエラーをすべて解決してください。
+
事前チェックがエラーなく完了すると、ファイルサーバーの一覧にファイルサーバー名が表示されます。表示されるファイルサーバーのドロップダウンには、設定されているゾーンが表示されます。



--
====


== エクスポート パスとディレクトリ パスを手動でアップロードします

NetApp Data Migratorを使用すると、NFSプロトコルを使用したデータ移行操作で使用するエクスポートパスとディレクトリパスを手動でアップロードできます。この機能は、NFSエクスポートパスの自動検出が利用できない環境において役立ちます。例えば、GCNV Flexサービスで使用する場合や、エクスポートパス全体ではなくディレクトリパスを移行する場合などに使用します。*エクスポートパス取得メカニズム*パネルで*手動アップロード*を選択した場合は、ファイルサーバーの作成が完了した後、NetApp Data Migratorが提供するテンプレートファイルをダウンロードして入力する必要があります。


NOTE: ディレクトリ レベルで移行を設定する必要がある場合は、このオプションを使用してください。移行対象がエクスポート全体ではなく特定のディレクトリである場合は、ディレクトリ パスを Excel スプレッドシートに直接入力してください。これにより、移行ワークフローはエクスポート レベルの入力を必要とせずに、各ディレクトリを個別に処理することが保証されます。

.手順
. 左側のナビゲーションパネルで、* Storage Servers * を選択します。
. *ファイル サーバー* を選択します。
. *[Click here to Upload Export Paths]*を選択します。
. *Download Template* を選択して、CSV ファイル テンプレートをダウンロードします。
. エクスポート パスとディレクトリ パスを CSV ファイルに保存します。
. *Click here to Upload Export Paths*を選択し、エクスポート パスとディレクトリ パスを含むCSVファイルを選択します。
+
エクスポート パスとディレクトリ パスは *Paths* の下に表示されます。

. エクスポート パスまたはディレクトリ パスを追加する必要がある場合は、ファイルに追加してから、*エクスポート パスの再アップロード* を選択します。


アップロードが完了すると、エクスポート パスとディレクトリ パスには次のいずれかのステータス タイプが表示されます：

* *Valid*：パスは正常にアップロードされ、このパスをマウントおよびアンマウントできます。
* *無効*：パスのアップロードに失敗しました。
* *無効*：パスは存在しますが、アップロードしたファイルに含まれていません。




== ファイル サーバの詳細を編集

必要に応じて、既に設定済みのファイルサーバーに変更を加えることができます。

「その他のNAS」または「Dell Isilon」ワークフローオプションを使用して、ファイルサーバーの詳細を編集します。

[role="tabbed-block"]
====
.NAS：その他
--
.手順
. 編集するファイルサーバーの横にあるアクションメニューを選択します。
. *Edit File Server* を選択します。*Upload Export Path Retrieval* に *Manual Upload* オプションを選択した場合、有効なパスのみが表示されます。
. *Server Type*タブを選択し、必要な編集を行ってから*Proceed*を選択します。
. *認証情報*タブを選択し、必要な編集を行った後、*続行*を選択します。
. *Workers*タブを選択し、必要な編集を行った後、*Submit*を選択してください。


--
.Dell Isilon
--
.手順
. 編集する親ファイルサーバーの横にあるアクションメニューを選択します。
. *Edit File Server* を選択します。
. *Server Type* タブを選択します。
+
.. 必要に応じて *Configuration Name* を更新してください。
.. 必要に応じて *Username* または *Password* を更新してください。
.. *続行*を選択します。


+

NOTE: *サーバータイプ*（Dell Isilon）と*管理ホスト*は変更できません。

. *Zone Credentials* タブを選択します：
+
.. 利用可能なリストから追加のゾーンを選択して、新しいゾーンを追加します。
.. 各ゾーンのプロトコルクレデンシャルを更新します：
+
必要に応じて、*NFS IP Address*、*Username*、または*Password*を更新してください。

+
必要に応じて、*SMB IP Address*、*Username*、または*Password*を更新してください。

.. *続行*を選択します。


. *Workers* タブを選択します。
+
.. 各ゾーンおよびプロトコルのワーカー割り当てを更新するには、*関連付け済み*列でワーカーのオン/オフを切り替えます。
.. 新しく割り当てられたワーカーに対して事前チェック検証を実行するには、*続行*を選択します。


. *Job Config* タブを選択します。
+
.. 必要に応じて *Working Directory* を更新してください。
.. *Finish* を選択します。




--
====