---
sidebar: sidebar 
permalink: manage-users.html 
keywords: user management, rbac, app admin, user accounts, access control 
summary: NetApp Data Migrator ユーザーをロールベースのアクセス制御で追加および管理します。アカウントの作成、ロールの割り当て、アクセスの有効化または無効化などが含まれます。 
---
= NetApp Data Migrator でのユーザーの追加と管理
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Data Migratorはlink:access-control.html["ロールベース アクセス制御（RBAC）"]を使用して、データ移行アクティビティを安全かつ効率的に管理します。コントロール仮想マシンとワーカー仮想マシン（VM）のセットアップ後、App Admin ユーザーは新しいユーザーにロールを作成して割り当てることができます。これにより、新しいユーザーは権限に応じて、ログイン、プロジェクトの表示または管理、その他の移行アクティビティを実行できるようになります。

.タスク概要
新規ユーザーの追加、既存ユーザーの有効化または無効化、あるいはユーザーパスワードのリセットを行うには、App Admin としてログインする必要があります。



== 新しいユーザを追加

新しいユーザーを作成し、一時パスワードを共有してください。

.手順
. NetApp Data Migratorにログインします。
. *設定*＞*ユーザー*を選択すると、登録済みユーザーのリストが表示されます。
. *ユーザーを追加*を選択します。
. 新規ユーザーの*名*、*姓*、および*メール*アドレスを入力してください。
. 新しいユーザーに管理者権限が必要な場合は、*App Admin* チェックボックスをオンにします。
. *Submit*を選択します。
. *Copy* リンク（パスワードフィールドの横）を選択して、マスク形式で表示される一時パスワードをコピーします。
. *閉じる*を選択します。
. コピーした一時パスワードを新しいユーザーと共有してください。新しいユーザーはそのパスワードを使ってログインできます。初回ログイン時には、パスワードの変更を求められます。




== 既存のユーザーを無効にする

他のユーザーのNetApp Data Migratorへのアクセスを無効にします。これにより、ユーザーはログインできなくなりますが、ユーザーデータや、そのユーザーに関連付けられた過去の移行ジョブやログは削除されません。

.手順
. ナビゲーションバーの *Settings* アイコンを選択します。
. *ユーザー*タブを選択すると、登録ユーザーのリストが表示されます。
. 無効化するユーザーの詳細の横にある *(⋮)* アイコンを選択し、ドロップダウンメニューから *Disable Access* を選択します。
+
ユーザーのステータスが*アクティブ*から*非アクティブ*に変更され、NetApp Data Migratorにログインできなくなります。





== ユーザーを有効にする

無効化されたユーザーのNetApp Data Migratorへのアクセスを復元し、割り当てられた権限に基づいてログインして操作を実行できるようにします。

.手順
. ナビゲーションバーの*設定*アイコンを選択します。
. *ユーザー*タブを選択すると、登録ユーザーのリストが表示されます。
. 有効化するユーザーの詳細の横にある *(⋮)* アイコンを選択し、ドロップダウンメニューから *Enable Access* を選択します。
+
ユーザーの状態が*非アクティブ*から*アクティブ*に変更されました。ユーザーはNetApp Data Migratorにログインできるようになりました。





== ユーザパスワードをリセットする

既存ユーザーのパスワードをリセットします。


NOTE: 他のApp Adminが利用できない場合にApp Adminユーザーのパスワードをリセットするには、ng-ndm-downloads@netapp.com に連絡してパスワードリセットスクリプトを入手してください。

.手順
. ナビゲーションバーの *Settings* アイコンを選択します。
. *ユーザー*タブを選択すると、登録ユーザーのリストが表示されます。
. パスワードをリセットする必要があるユーザーの詳細情報の横にある *(⋮)* アイコンを選択し、ドロップダウンメニューから *Reset Password* を選択します。
+
パスワードのリセットが成功したことを確認するメッセージが表示されます。

. *Copy* リンク（パスワードフィールドの横）を選択して、マスクされた形式で表示される一時パスワードをコピーします。
. コピーした一時パスワードをユーザーと共有します。

