---
sidebar: sidebar 
permalink: register-for-account.html 
keywords: netapp, data, migrator, new, support, register, account 
summary: NetAppを初めてご利用になるお客様は、NetAppアカウントを作成し、登録プロセスを完了してからNetApp Data Migratorにアクセスする必要があります。 
---
= NetApp Data Migratorにアクセスするためのアカウントを登録
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
新規のNetAppのお客様の場合、NetApp Data Migratorをダウンロードする前に、NetApp Support Siteでアカウントを登録する必要があります。すでにアカウントをお持ちの場合は、link:deploy-control-plane-and-linux-workers.html["NetApp Data MigratorのコントロールプレーンとLinuxワーカーVMをデプロイします"]に進むことができます。


NOTE: 新しいアカウントが*ゲストアクセス*から*フルアクセス*にアップグレードされるまでに、最大1営業日かかることがあります。

.手順
. ビジネスメールアドレスを使用してlink:https://mysupport.netapp.com/site/user/registration["NetAppサポート サイト"^]でアカウントを登録してください。
. *Submit*を選択します。
. 登録開始を認証するには、メールで送信されたワンタイムパスワードを入力してください。
. 登録完了ページで、必要な情報を入力してください：
+
.. ユーザーアクセスレベルには、*NetApp Customer/End User* を選択してください。
.. シリアル番号フィールドに、 `NDMNSSREG`を入力します。


. *Submit* を選択します。ユーザー登録が正常に送信されたことを示す確認ウィンドウが表示されます。


登録中に問題が発生した場合、または登録状況を確認したい場合は、link:https://mysupport.netapp.com/site/help["サポートチケットを開く"^]。

.次の手順
アカウント登録の方法を学んだら、link:deploy-control-plane-and-linux-workers.html["コントロールプレーンとLinuxワーカーVMを導入する"]。
