---
sidebar: sidebar 
permalink: upgrade.html 
keywords: upgrade, control plane, worker vm, upgrade bundle, version update 
summary: NetApp Data Migrator でコントロールプレーン、Linux ワーカー、または Windows ワーカーをアップグレードします。 
---
= NetApp Data Migratorのコントロールプレーンとワーカーをアップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Data Migrator では、コントロールプレーン、Linux ワーカー、または Windows ワーカーをアップグレードできます。

.開始する前に
* すべてのジョブ実行を停止し、すべてのジョブを非アクティブ状態にします。
* NetApp Support Siteからアップグレードバンドル（tar.gzファイル）をダウンロードし、ローカルディレクトリに保存します。
* 使用中のワーカーがオンラインであることを確認してください。アップグレード中にオフラインになっているワーカーはアップグレードされません。




== ステップ1：アップグレードバンドルをアップロードする

ローカルディレクトリからアップグレードバンドルをアップロードします。

.手順
. NetApp Data Migrator UIにログインし、ホームページに移動します。
. 右上隅にあるヘルプアイコンを選択します。
. *アップグレード*タブを選択します。
. *Select file*を選択し、アップグレードバンドルのtar.gzファイルを選択します。
. ファイルを選択した後、* Upload *を選択します。
+
アップロードと検証が完了したことを示すメッセージが表示されるまでお待ちください。

. 必要に応じて、*Start Over* を選択して別のファイルをアップロードすることで、プロセスを再度開始できます。




== ステップ2：コントロールプレーンとワーカーをアップグレードする

コントロールプレーンをアップグレードした後、LinuxワーカーまたはWindowsワーカーをアップグレードしてください。

.手順
. * Upgrade * を選択します。システムがコントロールプレーンのアップグレードを開始します。所要時間は約5～10分です。
+
アップグレード中は、アプリケーションが新しいバージョンで再起動されるため、UIが一時的に利用できなくなる場合があります。UIが再び利用可能になったら、再度ログインしてください。

. アップグレードが完了したら、*アップグレード*ページに戻ります。
. アップグレードのステータスが*Success*であることを確認してください。
. コントロールプレーンのアップグレードが正常に完了すると、オンラインのすべてのワーカーに対してワーカーのアップグレードが自動的に開始されます。
+

NOTE: オンラインワーカーは、新しいバージョンを自動的にインストールして再起動します。オフラインワーカーはアップグレードされません。

. ワーカーのアップグレードが自動的に開始されない場合は、SSHを使用してワーカーに接続し、アップグレードを開始してください：
+
[role="tabbed-block"]
====
.Linuxワーカー
--
[source, cli]
----
sudo /opt/datamigrator/staging/<version>/upgrade.sh <version>
----
--
.Windowsワーカー
--
[source, cli]
----
ExecutionPolicy Bypass -File C:\datamigrator\staging\<version>\upgrade.ps1 -Version <version>
----
--
====




== ステップ3：ログを表示してトラブルシューティングを行う

仮想マシンのログを表示して、アップグレード中に発生した問題のトラブルシューティングをサポートします。

.手順
. SSHを使用してコントロールプレーンVMに接続し、次のコマンドを実行してログを表示します：
+
[source, cli]
----
tail -f /upgrade/upgrade-<version>.log
----
. SSHを使用してLinuxワーカーまたはWindowsワーカーVMに接続し、以下のパスを使用してログを表示します：
+
[role="tabbed-block"]
====
.Linuxワーカー
--
[source, cli]
----
/opt/datamigrator/upgrade.log
----
--
.Windowsワーカー
--
[source, cli]
----
C:\datamigrator\upgrade.log
----
--
====
. アップグレードが失敗した場合、システムは自動的に以前のバージョンにロールバックし、UIにはアップグレードのステータスが*Failed*と表示されます。
+
Ansibleログを確認してから、NetAppサポートに連絡し、Ansibleログを通信に添付してください。


